-- Create expenses table
create table expenses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  category text not null,
  amount numeric not null,
  date date not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create appointments table
create table appointments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  date timestamp with time zone not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table expenses enable row level security;
alter table appointments enable row level security;

-- Create policies
create policy "Users can view their own expenses" on expenses
  for select using (auth.uid() = user_id);

create policy "Users can insert their own expenses" on expenses
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own expenses" on expenses
  for update using (auth.uid() = user_id);

create policy "Users can delete their own expenses" on expenses
  for delete using (auth.uid() = user_id);

create policy "Users can view their own appointments" on appointments
  for select using (auth.uid() = user_id);

create policy "Users can insert their own appointments" on appointments
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own appointments" on appointments
  for update using (auth.uid() = user_id);

create policy "Users can delete their own appointments" on appointments
  for delete using (auth.uid() = user_id);
